SELECT * FROM classicmodels.employees;
SELECT * FROM employees;
SELECT * FROM employees WHERE jobTitle = 'Sales Rep' AND employeeNumber BETWEEN 1200 AND 1500;
SELECT * FROM employees WHERE officeCode >= 2 AND jobTitle != 'Sales Rep';
SELECT * FROM customers WHERE country != 'USA';
SELECT * FROM customers WHERE customerNumber NOT BETWEEN 150 AND 200;
SELECT firstName, lastName AS 'Name of the employee' FROM employees ORDER BY lastName;
SELECT * FROM customers WHERE creditLimit > 70000 ORDER BY contactLastName DESC;
SELECT * FROM customers WHERE city IN ('Singapore', 'Liverpool', 'NYC');
SELECT * FROM customers WHERE contactLastName LIKE 'SMITH%';
SELECT * FROM employees WHERE officeCode IN (1, 3, 5);
SELECT * FROM customers WHERE creditLimit BETWEEN 50000 AND 95000;
SELECT * FROM employees WHERE officeCode NOT IN (1, 3);
SELECT * FROM customers WHERE customerName LIKE 'S%';
SELECT * FROM customers WHERE contactLastName LIKE 'S%H';
SELECT * FROM customers WHERE contactFirstName LIKE 'S___%';
SELECT * FROM customers WHERE LENGTH(contactFirstName) = 8;
SELECT * FROM customers WHERE customerName LIKE 'a%e';
SELECT * FROM customers WHERE customerName LIKE '%ee%';
SELECT officeCode, COUNT(*) AS employeeCount FROM employees GROUP BY officeCode;
SELECT state, MAX(creditLimit) AS maxCreditLimit FROM customers GROUP BY state;